infotv_image: tracon/infotv
infotv_hostname: infotv.tracon.fi
infotv_port: 8003
infotv_ssl: true
infotv_letsencrypt: true
infotv_ssl_certificate: /srv/letsencrypt/secrets/infotv.tracon.fi/chained.pem
infotv_ssl_certificate_key: /srv/letsencrypt/secrets/infotv.tracon.fi/domain.key
infotv_allowed_hosts: "{{Â infotv_hostname }}"
infotv_default_from_email: suunnistajat@kompassi.eu
infotv_email_host: sr1.gw0.fi
infotv_admins: "Santtu Pajukanta <santtu@pajukanta.fi>"
infotv_postgresql_container: nuoli.tracon.fi-postgres
infotv_postgresql_username: infotv
infotv_postgresql_database: infotv
infotv_workers: 2
infotv_default_event: kuplii2017
